version: 0.2
env:
  variables:
    taito_mode: "ci"

phases:
  pre_build:
    commands:
      # Determine ENV and IMAGE_TAG
      - export ENV=$(git branch -a --contains HEAD | sed -n 2p | awk '{ printf $1 }' | xargs echo $CODEBUILD_WEBHOOK_HEAD_REF | awk '{ printf $1 }' | sed 's/.*\///')
      - export IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
      # TODO: Cancel other ongoing builds for $ENV
      # - taito deployment cancel:$ENV $CURRENT_BUILD_ID
      # Prepare build
      - taito build prepare:$ENV $IMAGE_TAG
  build:
    commands:
      # Prepare artifacts for deployment
      - taito artifact prepare:wordpress:$ENV $IMAGE_TAG
      - taito wp-plugin-update:$${branch_name} || echo "WARNING: Failed updating wordpress plugins"
      # Deploy changes to target environment
      - taito deployment deploy:$ENV $IMAGE_TAG
      # Release artifacts
      - taito artifact release:wordpress:$ENV $IMAGE_TAG
      # Release build
      - taito build release:$ENV
