images: [
  'eu.gcr.io/$PROJECT_ID/$_REPO_NAME/wordpress:$COMMIT_SHA'
]

timeout: 1500s

# If you want to grant outsiders access to your build logs, you mey save
# the logs to a separate bucket and grant the outsiders access to that bucket
# logsBucket: 'gs://my-builds' # TODO _TEMPLATE_DEFAULT for this also

substitutions:
  _REPO_NAME: wordpress-template
  # NOTE: These are removed by 'taito project create'
  _TEMPLATE_DEFAULT_TAITO_IMAGE:
  _TEMPLATE_DEFAULT_ORGANIZATION:
  _TEMPLATE_DEFAULT_ORGANIZATION_ABBR:
  _TEMPLATE_DEFAULT_VC_ORGANIZATION:
  _TEMPLATE_DEFAULT_VC_URL:
  _TEMPLATE_DEFAULT_SENTRY_ORGANIZATION:
  _TEMPLATE_DEFAULT_DOMAIN:
  _TEMPLATE_DEFAULT_DOMAIN_PROD:
  _TEMPLATE_DEFAULT_ZONE:
  _TEMPLATE_DEFAULT_ZONE_PROD:
  _TEMPLATE_DEFAULT_PROVIDER:
  _TEMPLATE_DEFAULT_PROVIDER_PROD:
  _TEMPLATE_DEFAULT_PROVIDER_ORG_ID:
  _TEMPLATE_DEFAULT_PROVIDER_ORG_ID_PROD:
  _TEMPLATE_DEFAULT_PROVIDER_REGION:
  _TEMPLATE_DEFAULT_PROVIDER_REGION_PROD:
  _TEMPLATE_DEFAULT_PROVIDER_ZONE:
  _TEMPLATE_DEFAULT_PROVIDER_ZONE_PROD:
  _TEMPLATE_DEFAULT_UPTIME_CHANNELS_PROD:
  _TEMPLATE_DEFAULT_CI_PROVIDER:
  _TEMPLATE_DEFAULT_CI_PROVIDER_PROD:
  _TEMPLATE_DEFAULT_VC_PROVIDER:
  _TEMPLATE_DEFAULT_CONTAINER_REGISTRY:
  _TEMPLATE_DEFAULT_CONTAINER_REGISTRY_PROD:
  _TEMPLATE_DEFAULT_KUBERNETES:
  _TEMPLATE_DEFAULT_KUBERNETES_CLUSTER_PREFIX:
  _TEMPLATE_DEFAULT_KUBERNETES_CLUSTER_PREFIX_PROD:
  _TEMPLATE_DEFAULT_MYSQL:
  _TEMPLATE_DEFAULT_MYSQL_HOST:
  _TEMPLATE_DEFAULT_MYSQL_HOST_PROD:
  _TEMPLATE_DEFAULT_MYSQL_MASTER_USERNAME:
  _TEMPLATE_DEFAULT_MYSQL_MASTER_PASSWORD_HINT:

steps:

# NOTE: This first ugly step is an optimization. We execute cancel with
# the google provided kubectl container instead of Taito CLI, because it
# doesn't need to be pulled before execution -> cancel executes immediately.
- id: manual-cancel
  name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  env:
    - branch_name=$BRANCH_NAME
    - commit_sha=$COMMIT_SHA
    - build_id=$BUILD_ID
    - full_repo_name=$_REPO_NAME
    - image_path=eu.gcr.io/$PROJECT_ID/$_REPO_NAME/wordpress:$COMMIT_SHA
  args:
  - '-c'
  - |
    # NOTE: These are removed by 'taito project create'
    export template_default_taito_image=${_TEMPLATE_DEFAULT_TAITO_IMAGE}
    export template_default_organization=${_TEMPLATE_DEFAULT_ORGANIZATION}
    export template_default_organization_abbr=${_TEMPLATE_DEFAULT_ORGANIZATION_ABBR}
    export template_default_vc_organization=${_TEMPLATE_DEFAULT_VC_ORGANIZATION}
    export template_default_vc_url=${_TEMPLATE_DEFAULT_VC_URL}
    export template_default_sentry_organization=${_TEMPLATE_DEFAULT_SENTRY_ORGANIZATION}
    export template_default_domain=${_TEMPLATE_DEFAULT_DOMAIN}
    export template_default_domain_prod=${_TEMPLATE_DEFAULT_DOMAIN_PROD}
    export template_default_zone=${_TEMPLATE_DEFAULT_ZONE}
    export template_default_zone_prod=${_TEMPLATE_DEFAULT_ZONE_PROD}
    export template_default_provider=${_TEMPLATE_DEFAULT_PROVIDER}
    export template_default_provider_prod=${_TEMPLATE_DEFAULT_PROVIDER_PROD}
    export template_default_provider_org_id=${_TEMPLATE_DEFAULT_PROVIDER_ORG_ID}
    export template_default_provider_org_id_prod=${_TEMPLATE_DEFAULT_PROVIDER_ORG_ID_PROD}
    export template_default_provider_region=${_TEMPLATE_DEFAULT_PROVIDER_REGION}
    export template_default_provider_region_prod=${_TEMPLATE_DEFAULT_PROVIDER_REGION_PROD}
    export template_default_provider_zone=${_TEMPLATE_DEFAULT_PROVIDER_ZONE}
    export template_default_provider_zone_prod=${_TEMPLATE_DEFAULT_PROVIDER_ZONE_PROD}
    export template_default_uptime_channels_prod=${_TEMPLATE_DEFAULT_UPTIME_CHANNELS_PROD}
    export template_default_ci_provider=${_TEMPLATE_DEFAULT_CI_PROVIDER}
    export template_default_ci_provider_prod=${_TEMPLATE_DEFAULT_CI_PROVIDER_PROD}
    export template_default_vc_provider=${_TEMPLATE_DEFAULT_VC_PROVIDER}
    export template_default_container_registry=${_TEMPLATE_DEFAULT_CONTAINER_REGISTRY}
    export template_default_container_registry_prod=${_TEMPLATE_DEFAULT_CONTAINER_REGISTRY_PROD}
    export template_default_kubernetes=${_TEMPLATE_DEFAULT_KUBERNETES}
    export template_default_kubernetes_cluster_prefix=${_TEMPLATE_DEFAULT_KUBERNETES_CLUSTER_PREFIX}
    export template_default_kubernetes_cluster_prefix_prod=${_TEMPLATE_DEFAULT_KUBERNETES_CLUSTER_PREFIX_PROD}
    export template_default_mysql=${_TEMPLATE_DEFAULT_MYSQL}
    export template_default_mysql_host=${_TEMPLATE_DEFAULT_MYSQL_HOST}
    export template_default_mysql_host_prod=${_TEMPLATE_DEFAULT_MYSQL_HOST_PROD}
    export template_default_mysql_master_username=${_TEMPLATE_DEFAULT_MYSQL_MASTER_USERNAME}
    export template_default_mysql_master_password_hint=${_TEMPLATE_DEFAULT_MYSQL_MASTER_PASSWORD_HINT}

    export taito_target_env
    taito_target_env="$${branch_name}"
    if [[ "$${taito_target_env}" == "master" ]]; then
      taito_target_env="prod"
    fi
    export taito_env="$${taito_target_env}"
    source ./taito-config.sh

    # TODO: should be implemented in Taito CLI plugin
    echo "- Get cluster credentials"
    if ! gcloud container clusters get-credentials "$${kubernetes_name}" \
      --zone "$${taito_provider_zone}"; then
      echo "ERROR: Get cluster credentials failed"
      exit 1
    fi

    echo "- Cancel all previous ongoing builds targetting the same branch"
    gcloud builds list --ongoing | \
      grep "$${full_repo_name}@$${branch_name}" | \
      grep -v "$${build_id}" | \
      cut -d ' ' -f 1 | \
      xargs -L1 gcloud builds cancel 2> /dev/null

    echo "- We ignore all fails during cancel (hence the last echo)"


# ----------------------- Taito CLI ----------------------------------

# Prepare build

- id: build-prepare
  waitFor: ['-']
  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
  args: ['build-prepare:$BRANCH_NAME', '$COMMIT_SHA']
  env:
    - taito_mode=ci
    # NOTE: These are removed by 'taito project create'
    - template_default_taito_image=${_TEMPLATE_DEFAULT_TAITO_IMAGE}
    - template_default_organization=${_TEMPLATE_DEFAULT_ORGANIZATION}
    - template_default_organization_abbr=${_TEMPLATE_DEFAULT_ORGANIZATION_ABBR}
    - template_default_vc_organization=${_TEMPLATE_DEFAULT_VC_ORGANIZATION}
    - template_default_vc_url=${_TEMPLATE_DEFAULT_VC_URL}
    - template_default_sentry_organization=${_TEMPLATE_DEFAULT_SENTRY_ORGANIZATION}
    - template_default_domain=${_TEMPLATE_DEFAULT_DOMAIN}
    - template_default_domain_prod=${_TEMPLATE_DEFAULT_DOMAIN_PROD}
    - template_default_zone=${_TEMPLATE_DEFAULT_ZONE}
    - template_default_zone_prod=${_TEMPLATE_DEFAULT_ZONE_PROD}
    - template_default_provider=${_TEMPLATE_DEFAULT_PROVIDER}
    - template_default_provider_prod=${_TEMPLATE_DEFAULT_PROVIDER_PROD}
    - template_default_provider_org_id=${_TEMPLATE_DEFAULT_PROVIDER_ORG_ID}
    - template_default_provider_org_id_prod=${_TEMPLATE_DEFAULT_PROVIDER_ORG_ID_PROD}
    - template_default_provider_region=${_TEMPLATE_DEFAULT_PROVIDER_REGION}
    - template_default_provider_region_prod=${_TEMPLATE_DEFAULT_PROVIDER_REGION_PROD}
    - template_default_provider_zone=${_TEMPLATE_DEFAULT_PROVIDER_ZONE}
    - template_default_provider_zone_prod=${_TEMPLATE_DEFAULT_PROVIDER_ZONE_PROD}
    - template_default_uptime_channels_prod=${_TEMPLATE_DEFAULT_UPTIME_CHANNELS_PROD}
    - template_default_ci_provider=${_TEMPLATE_DEFAULT_CI_PROVIDER}
    - template_default_ci_provider_prod=${_TEMPLATE_DEFAULT_CI_PROVIDER_PROD}
    - template_default_vc_provider=${_TEMPLATE_DEFAULT_VC_PROVIDER}
    - template_default_container_registry=${_TEMPLATE_DEFAULT_CONTAINER_REGISTRY}
    - template_default_container_registry_prod=${_TEMPLATE_DEFAULT_CONTAINER_REGISTRY_PROD}
    - template_default_kubernetes=${_TEMPLATE_DEFAULT_KUBERNETES}
    - template_default_kubernetes_cluster_prefix=${_TEMPLATE_DEFAULT_KUBERNETES_CLUSTER_PREFIX}
    - template_default_kubernetes_cluster_prefix_prod=${_TEMPLATE_DEFAULT_KUBERNETES_CLUSTER_PREFIX_PROD}
    - template_default_mysql=${_TEMPLATE_DEFAULT_MYSQL}
    - template_default_mysql_host=${_TEMPLATE_DEFAULT_MYSQL_HOST}
    - template_default_mysql_host_prod=${_TEMPLATE_DEFAULT_MYSQL_HOST_PROD}
    - template_default_mysql_master_username=${_TEMPLATE_DEFAULT_MYSQL_MASTER_USERNAME}
    - template_default_mysql_master_password_hint=${_TEMPLATE_DEFAULT_MYSQL_MASTER_PASSWORD_HINT}

# Prepare artifacts for deployment
# TODO build/push only if persistence is false

- id: artifact-prepare-wordpress
  waitFor: ['build-prepare']
  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
  args: ['artifact-prepare:wordpress:$BRANCH_NAME', '$COMMIT_SHA']
  env:
    - taito_mode=ci
    # NOTE: These are removed by 'taito project create'
    - template_default_taito_image=${_TEMPLATE_DEFAULT_TAITO_IMAGE}
    - template_default_organization=${_TEMPLATE_DEFAULT_ORGANIZATION}
    - template_default_organization_abbr=${_TEMPLATE_DEFAULT_ORGANIZATION_ABBR}
    - template_default_vc_organization=${_TEMPLATE_DEFAULT_VC_ORGANIZATION}
    - template_default_vc_url=${_TEMPLATE_DEFAULT_VC_URL}
    - template_default_sentry_organization=${_TEMPLATE_DEFAULT_SENTRY_ORGANIZATION}
    - template_default_domain=${_TEMPLATE_DEFAULT_DOMAIN}
    - template_default_domain_prod=${_TEMPLATE_DEFAULT_DOMAIN_PROD}
    - template_default_zone=${_TEMPLATE_DEFAULT_ZONE}
    - template_default_zone_prod=${_TEMPLATE_DEFAULT_ZONE_PROD}
    - template_default_provider=${_TEMPLATE_DEFAULT_PROVIDER}
    - template_default_provider_prod=${_TEMPLATE_DEFAULT_PROVIDER_PROD}
    - template_default_provider_org_id=${_TEMPLATE_DEFAULT_PROVIDER_ORG_ID}
    - template_default_provider_org_id_prod=${_TEMPLATE_DEFAULT_PROVIDER_ORG_ID_PROD}
    - template_default_provider_region=${_TEMPLATE_DEFAULT_PROVIDER_REGION}
    - template_default_provider_region_prod=${_TEMPLATE_DEFAULT_PROVIDER_REGION_PROD}
    - template_default_provider_zone=${_TEMPLATE_DEFAULT_PROVIDER_ZONE}
    - template_default_provider_zone_prod=${_TEMPLATE_DEFAULT_PROVIDER_ZONE_PROD}
    - template_default_uptime_channels_prod=${_TEMPLATE_DEFAULT_UPTIME_CHANNELS_PROD}
    - template_default_ci_provider=${_TEMPLATE_DEFAULT_CI_PROVIDER}
    - template_default_ci_provider_prod=${_TEMPLATE_DEFAULT_CI_PROVIDER_PROD}
    - template_default_vc_provider=${_TEMPLATE_DEFAULT_VC_PROVIDER}
    - template_default_container_registry=${_TEMPLATE_DEFAULT_CONTAINER_REGISTRY}
    - template_default_container_registry_prod=${_TEMPLATE_DEFAULT_CONTAINER_REGISTRY_PROD}
    - template_default_kubernetes=${_TEMPLATE_DEFAULT_KUBERNETES}
    - template_default_kubernetes_cluster_prefix=${_TEMPLATE_DEFAULT_KUBERNETES_CLUSTER_PREFIX}
    - template_default_kubernetes_cluster_prefix_prod=${_TEMPLATE_DEFAULT_KUBERNETES_CLUSTER_PREFIX_PROD}
    - template_default_mysql=${_TEMPLATE_DEFAULT_MYSQL}
    - template_default_mysql_host=${_TEMPLATE_DEFAULT_MYSQL_HOST}
    - template_default_mysql_host_prod=${_TEMPLATE_DEFAULT_MYSQL_HOST_PROD}
    - template_default_mysql_master_username=${_TEMPLATE_DEFAULT_MYSQL_MASTER_USERNAME}
    - template_default_mysql_master_password_hint=${_TEMPLATE_DEFAULT_MYSQL_MASTER_PASSWORD_HINT}

# Update wordpress plugins

- id: wp-plugin-update
  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
  env:
    - taito_mode=ci
    - branch_name=$BRANCH_NAME
    # NOTE: These are removed by 'taito project create'
    - template_default_taito_image=${_TEMPLATE_DEFAULT_TAITO_IMAGE}
    - template_default_organization=${_TEMPLATE_DEFAULT_ORGANIZATION}
    - template_default_organization_abbr=${_TEMPLATE_DEFAULT_ORGANIZATION_ABBR}
    - template_default_vc_organization=${_TEMPLATE_DEFAULT_VC_ORGANIZATION}
    - template_default_vc_url=${_TEMPLATE_DEFAULT_VC_URL}
    - template_default_sentry_organization=${_TEMPLATE_DEFAULT_SENTRY_ORGANIZATION}
    - template_default_domain=${_TEMPLATE_DEFAULT_DOMAIN}
    - template_default_domain_prod=${_TEMPLATE_DEFAULT_DOMAIN_PROD}
    - template_default_zone=${_TEMPLATE_DEFAULT_ZONE}
    - template_default_zone_prod=${_TEMPLATE_DEFAULT_ZONE_PROD}
    - template_default_provider=${_TEMPLATE_DEFAULT_PROVIDER}
    - template_default_provider_prod=${_TEMPLATE_DEFAULT_PROVIDER_PROD}
    - template_default_provider_org_id=${_TEMPLATE_DEFAULT_PROVIDER_ORG_ID}
    - template_default_provider_org_id_prod=${_TEMPLATE_DEFAULT_PROVIDER_ORG_ID_PROD}
    - template_default_provider_region=${_TEMPLATE_DEFAULT_PROVIDER_REGION}
    - template_default_provider_region_prod=${_TEMPLATE_DEFAULT_PROVIDER_REGION_PROD}
    - template_default_provider_zone=${_TEMPLATE_DEFAULT_PROVIDER_ZONE}
    - template_default_provider_zone_prod=${_TEMPLATE_DEFAULT_PROVIDER_ZONE_PROD}
    - template_default_uptime_channels_prod=${_TEMPLATE_DEFAULT_UPTIME_CHANNELS_PROD}
    - template_default_ci_provider=${_TEMPLATE_DEFAULT_CI_PROVIDER}
    - template_default_ci_provider_prod=${_TEMPLATE_DEFAULT_CI_PROVIDER_PROD}
    - template_default_vc_provider=${_TEMPLATE_DEFAULT_VC_PROVIDER}
    - template_default_container_registry=${_TEMPLATE_DEFAULT_CONTAINER_REGISTRY}
    - template_default_container_registry_prod=${_TEMPLATE_DEFAULT_CONTAINER_REGISTRY_PROD}
    - template_default_kubernetes=${_TEMPLATE_DEFAULT_KUBERNETES}
    - template_default_kubernetes_cluster_prefix=${_TEMPLATE_DEFAULT_KUBERNETES_CLUSTER_PREFIX}
    - template_default_kubernetes_cluster_prefix_prod=${_TEMPLATE_DEFAULT_KUBERNETES_CLUSTER_PREFIX_PROD}
    - template_default_mysql=${_TEMPLATE_DEFAULT_MYSQL}
    - template_default_mysql_host=${_TEMPLATE_DEFAULT_MYSQL_HOST}
    - template_default_mysql_host_prod=${_TEMPLATE_DEFAULT_MYSQL_HOST_PROD}
    - template_default_mysql_master_username=${_TEMPLATE_DEFAULT_MYSQL_MASTER_USERNAME}
    - template_default_mysql_master_password_hint=${_TEMPLATE_DEFAULT_MYSQL_MASTER_PASSWORD_HINT}
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    taito wp-plugin-update:$${branch_name} || \
      echo "WARNING: Failed updating wordpress plugins"

# Deploy to target environment

- id: deployment-deploy
  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
  args: ['deployment-deploy:$BRANCH_NAME', '$COMMIT_SHA']
  env:
    - taito_mode=ci
    # NOTE: These are removed by 'taito project create'
    - template_default_taito_image=${_TEMPLATE_DEFAULT_TAITO_IMAGE}
    - template_default_organization=${_TEMPLATE_DEFAULT_ORGANIZATION}
    - template_default_organization_abbr=${_TEMPLATE_DEFAULT_ORGANIZATION_ABBR}
    - template_default_vc_organization=${_TEMPLATE_DEFAULT_VC_ORGANIZATION}
    - template_default_vc_url=${_TEMPLATE_DEFAULT_VC_URL}
    - template_default_sentry_organization=${_TEMPLATE_DEFAULT_SENTRY_ORGANIZATION}
    - template_default_domain=${_TEMPLATE_DEFAULT_DOMAIN}
    - template_default_domain_prod=${_TEMPLATE_DEFAULT_DOMAIN_PROD}
    - template_default_zone=${_TEMPLATE_DEFAULT_ZONE}
    - template_default_zone_prod=${_TEMPLATE_DEFAULT_ZONE_PROD}
    - template_default_provider=${_TEMPLATE_DEFAULT_PROVIDER}
    - template_default_provider_prod=${_TEMPLATE_DEFAULT_PROVIDER_PROD}
    - template_default_provider_org_id=${_TEMPLATE_DEFAULT_PROVIDER_ORG_ID}
    - template_default_provider_org_id_prod=${_TEMPLATE_DEFAULT_PROVIDER_ORG_ID_PROD}
    - template_default_provider_region=${_TEMPLATE_DEFAULT_PROVIDER_REGION}
    - template_default_provider_region_prod=${_TEMPLATE_DEFAULT_PROVIDER_REGION_PROD}
    - template_default_provider_zone=${_TEMPLATE_DEFAULT_PROVIDER_ZONE}
    - template_default_provider_zone_prod=${_TEMPLATE_DEFAULT_PROVIDER_ZONE_PROD}
    - template_default_uptime_channels_prod=${_TEMPLATE_DEFAULT_UPTIME_CHANNELS_PROD}
    - template_default_ci_provider=${_TEMPLATE_DEFAULT_CI_PROVIDER}
    - template_default_ci_provider_prod=${_TEMPLATE_DEFAULT_CI_PROVIDER_PROD}
    - template_default_vc_provider=${_TEMPLATE_DEFAULT_VC_PROVIDER}
    - template_default_container_registry=${_TEMPLATE_DEFAULT_CONTAINER_REGISTRY}
    - template_default_container_registry_prod=${_TEMPLATE_DEFAULT_CONTAINER_REGISTRY_PROD}
    - template_default_kubernetes=${_TEMPLATE_DEFAULT_KUBERNETES}
    - template_default_kubernetes_cluster_prefix=${_TEMPLATE_DEFAULT_KUBERNETES_CLUSTER_PREFIX}
    - template_default_kubernetes_cluster_prefix_prod=${_TEMPLATE_DEFAULT_KUBERNETES_CLUSTER_PREFIX_PROD}
    - template_default_mysql=${_TEMPLATE_DEFAULT_MYSQL}
    - template_default_mysql_host=${_TEMPLATE_DEFAULT_MYSQL_HOST}
    - template_default_mysql_host_prod=${_TEMPLATE_DEFAULT_MYSQL_HOST_PROD}
    - template_default_mysql_master_username=${_TEMPLATE_DEFAULT_MYSQL_MASTER_USERNAME}
    - template_default_mysql_master_password_hint=${_TEMPLATE_DEFAULT_MYSQL_MASTER_PASSWORD_HINT}

# Release build

- id: build-release
  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
  args: ['build-release:$BRANCH_NAME']
  env:
    - taito_mode=ci
    # NOTE: These are removed by 'taito project create'
    - template_default_taito_image=${_TEMPLATE_DEFAULT_TAITO_IMAGE}
    - template_default_organization=${_TEMPLATE_DEFAULT_ORGANIZATION}
    - template_default_organization_abbr=${_TEMPLATE_DEFAULT_ORGANIZATION_ABBR}
    - template_default_vc_organization=${_TEMPLATE_DEFAULT_VC_ORGANIZATION}
    - template_default_vc_url=${_TEMPLATE_DEFAULT_VC_URL}
    - template_default_sentry_organization=${_TEMPLATE_DEFAULT_SENTRY_ORGANIZATION}
    - template_default_domain=${_TEMPLATE_DEFAULT_DOMAIN}
    - template_default_domain_prod=${_TEMPLATE_DEFAULT_DOMAIN_PROD}
    - template_default_zone=${_TEMPLATE_DEFAULT_ZONE}
    - template_default_zone_prod=${_TEMPLATE_DEFAULT_ZONE_PROD}
    - template_default_provider=${_TEMPLATE_DEFAULT_PROVIDER}
    - template_default_provider_prod=${_TEMPLATE_DEFAULT_PROVIDER_PROD}
    - template_default_provider_org_id=${_TEMPLATE_DEFAULT_PROVIDER_ORG_ID}
    - template_default_provider_org_id_prod=${_TEMPLATE_DEFAULT_PROVIDER_ORG_ID_PROD}
    - template_default_provider_region=${_TEMPLATE_DEFAULT_PROVIDER_REGION}
    - template_default_provider_region_prod=${_TEMPLATE_DEFAULT_PROVIDER_REGION_PROD}
    - template_default_provider_zone=${_TEMPLATE_DEFAULT_PROVIDER_ZONE}
    - template_default_provider_zone_prod=${_TEMPLATE_DEFAULT_PROVIDER_ZONE_PROD}
    - template_default_uptime_channels_prod=${_TEMPLATE_DEFAULT_UPTIME_CHANNELS_PROD}
    - template_default_ci_provider=${_TEMPLATE_DEFAULT_CI_PROVIDER}
    - template_default_ci_provider_prod=${_TEMPLATE_DEFAULT_CI_PROVIDER_PROD}
    - template_default_vc_provider=${_TEMPLATE_DEFAULT_VC_PROVIDER}
    - template_default_container_registry=${_TEMPLATE_DEFAULT_CONTAINER_REGISTRY}
    - template_default_container_registry_prod=${_TEMPLATE_DEFAULT_CONTAINER_REGISTRY_PROD}
    - template_default_kubernetes=${_TEMPLATE_DEFAULT_KUBERNETES}
    - template_default_kubernetes_cluster_prefix=${_TEMPLATE_DEFAULT_KUBERNETES_CLUSTER_PREFIX}
    - template_default_kubernetes_cluster_prefix_prod=${_TEMPLATE_DEFAULT_KUBERNETES_CLUSTER_PREFIX_PROD}
    - template_default_mysql=${_TEMPLATE_DEFAULT_MYSQL}
    - template_default_mysql_host=${_TEMPLATE_DEFAULT_MYSQL_HOST}
    - template_default_mysql_host_prod=${_TEMPLATE_DEFAULT_MYSQL_HOST_PROD}
    - template_default_mysql_master_username=${_TEMPLATE_DEFAULT_MYSQL_MASTER_USERNAME}
    - template_default_mysql_master_password_hint=${_TEMPLATE_DEFAULT_MYSQL_MASTER_PASSWORD_HINT}
