wordpress-template-wordpress:
  container_name: wordpress-template-wordpress
  image: bitnami/wordpress:4.9.6
  restart: on-failure
  ports:
    - "4635:80"
  links:
    - wordpress-template-database:wordpress-template-database
  volumes:
    - "./wordpress/data:/bitnami"
  environment:
    WORDPRESS_USERNAME: admin
    WORDPRESS_PASSWORD: pass
    MARIADB_HOST: wordpress-template-database
    MARIADB_PORT_NUMBER: 3306
    WORDPRESS_DATABASE_NAME: wordpress_template_local
    WORDPRESS_DATABASE_USER: wordpress_template_local_app
    WORDPRESS_DATABASE_PASSWORD: secret

wordpress-template-database:
  container_name: wordpress-template-database
  image: mysql:5.7
  restart: on-failure
  ports:
    - "7587:3306"
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: wordpress_template_local
    MYSQL_USER: wordpress_template_local_app
    MYSQL_PASSWORD: secret
