version: '3.5'
services:
  wordpress-template-wordpress:
    container_name: wordpress-template-wordpress
    build:
      context: ./wordpress
      dockerfile: ${dockerfile}
    restart: unless-stopped
    networks:
      - default
    ports:
      - "127.0.0.1:4635:80"
    volumes:
      - "./wordpress/data:${DC_PATH}/bitnami:delegated"
    environment:
      DC_COMMAND: ${DC_COMMAND}
      HOST_UNAME: ${taito_host_uname}
      COMMON_PUBLIC_PORT: 4635
      WORDPRESS_USERNAME: deleteme    # SHOW ON INFO
      WORDPRESS_PASSWORD: password-change-it-7983p4nWgRE2p4No2d9 # SHOW ON INFO
      MARIADB_HOST: wordpress-template-database
      MARIADB_PORT_NUMBER: 3306
      # NOTE: For staging database
      # WORDPRESS_DATABASE_NAME: wptemplatestag
      # WORDPRESS_DATABASE_USER: wptemplatestag
      # WORDPRESS_DATABASE_PASSWORD: TODO add_passwd_here # TODO: fetch automatically from kubernetes
      # NOTE: For local database
      WORDPRESS_DATABASE_NAME: wptemplatelocal
      WORDPRESS_DATABASE_USER: wptemplatelocal
      WORDPRESS_DATABASE_PASSWORD: ${taito_default_password}

  # NOTE: For staging database
  # wordpress-template-database:
  #   container_name: wordpress-template-database
  #   image: ${taito_image:-taitounited/taito-cli:latest}
  #   restart: unless-stopped
  #   entrypoint: /bin/sh -c "cd /project && taito db-proxy:stag 3306"
  #   user: taito
  #   networks:
  #     - default
  #   ports:
  #     - "127.0.0.1:7587:3306"
  #   volumes:
  #     - ".:/project:delegated"
  #   environment:
  #     taito_docker: 'true'

  # NOTE: For local database
  wordpress-template-database:
    container_name: wordpress-template-database
    image: mysql:5.7
    restart: unless-stopped
    networks:
      - default
    ports:
      - "127.0.0.1:7587:3306"
    environment:
      MYSQL_DATABASE: wptemplatelocal
      MYSQL_USER: wptemplatelocal
      MYSQL_PASSWORD: ${taito_default_password}
      MYSQL_ROOT_PASSWORD: ${taito_default_password}

networks:
  default:
