# This file is used to run your application locally with Docker Compose

version: '3.8'
services:
  wordpress-template-wordpress:
    container_name: wordpress-template-wordpress
    build:
      context: ./wordpress
      dockerfile: ${dockerfile}
      args:
        USER_UID: ${taito_host_user_uid}
    restart: unless-stopped
    networks:
      - default
    ports:
      - "127.0.0.1:4635:8080"
    volumes:
      - "./wordpress/data:/bitnami:delegated"
    user: ${taito_host_user_uid}:0
    environment:
      COMMON_PUBLIC_PORT: 4635
      WORDPRESS_USERNAME: deleteme    # SHOW ON INFO
      WORDPRESS_PASSWORD: password-change-it-7983p4nWgRE2p4No2d9 # SHOW ON INFO
      WORDPRESS_DATABASE_HOST: wordpress-template-database
      WORDPRESS_DATABASE_PORT_NUMBER: 3306
      # NOTE: For staging database
      # WORDPRESS_DATABASE_NAME: wptemplatestag
      # WORDPRESS_DATABASE_USER: wptemplatestag
      # WORDPRESS_DATABASE_PASSWORD: TODO add_passwd_here # TODO: fetch automatically from kubernetes
      # NOTE: For local database
      WORDPRESS_DATABASE_NAME: wptemplatelocal
      WORDPRESS_DATABASE_USER: wptemplatelocala
      WORDPRESS_DATABASE_PASSWORD: ${taito_default_password}

  # NOTE: For staging database
  # wordpress-template-database:
  #   container_name: wordpress-template-database
  #   image: ${taito_image:-ghcr.io/taitounited/taito-cli:latest}
  #   restart: unless-stopped
  #   entrypoint: /bin/sh -c "cd /project && taito db-proxy:stag 3306"
  #   user: taito
  #   networks:
  #     - default
  #   ports:
  #     - "127.0.0.1:7587:3306"
  #   volumes:
  #     - ".:/project:delegated"
  #     # Mount cloud credentials for db proxy
  #     - "${HOME}/.aws:/home/taito/.aws"
  #     - "${HOME}/.azure:/home/taito/.azure"
  #     - "${HOME}/.config/doctl:/home/taito/.config/doctl"
  #     - "${HOME}/.config/gcloud:/home/taito/.config/gcloud"
  #     - "${HOME}/.kube:/home/taito/.kube"
  #   environment:
  #     taito_docker: 'true'

  # NOTE: For local database
  wordpress-template-database:
    container_name: wordpress-template-database
    image: mysql:5.7
    restart: unless-stopped
    networks:
      - default
    ports:
      - "127.0.0.1:7587:3306"
    environment:
      MYSQL_DATABASE: wptemplatelocal
      MYSQL_USER: wptemplatelocala
      MYSQL_PASSWORD: ${taito_default_password}
      MYSQL_ROOT_PASSWORD: ${taito_default_password}

networks:
  default:
