FROM bitnami/wordpress:5.0.2 as builder

COPY *.sh *.js /template/
RUN cp /app-entrypoint.sh /app-entrypoint-orig.sh
RUN cat /template/init.sh > /template/temp.sh && \
  cat /app-entrypoint.sh | grep -v '#!/' >> /template/temp.sh && \
  mv /template/temp.sh /app-entrypoint.sh && \
  chmod +x /app-entrypoint.sh

COPY ./data /bitnami-data
RUN ln -s /bitnami-data /bitnami
