{{- $root := . -}}
{{- range $host := .Values.wordpress.ingress.hosts }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ $host.name }}-cert
  labels:
    app: {{ template "fullname" $root }}
    chart: "{{ $root.Chart.Name }}-{{ $root.Chart.Version }}"
    release: "{{ $root.Release.Name }}"
    heritage: "{{ $root.Release.Service }}"
spec:
  secretName: {{ $host.tlsSecret }}
  issuerRef:
    name: common-letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
    - {{ $host.name }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
        - {{ $host.name }}
---
{{- end }}
