name: CI/CD Pipeline
on:
  push:
    branches:
      - dev
      - test
      - uat
      - stag
      - canary
      - prod
      - master
      - main

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-latest
    timeout-minutes: 50
    container:
      image: taitounited/taito-cli:ci-azure
      env:
        taito_mode: ci
        taito_image: taitounited/taito-cli:ci-azure
        taito_ci_phases:
        IMAGE_TAG: ${{ github.sha }}
        DOCKER_HOST_PATH: /home/runner/work/wordpress-template/wordpress-template
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    steps:
      # Init
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set environment
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set authentication
        run: |
          if [ ! -z "${{ secrets[format('{0}_AZURE_CLIENT_ID', env.BRANCH)] }}" ]; then
            echo "AZURE_CLIENT_ID=${{ secrets[format('{0}_AZURE_CLIENT_ID', env.BRANCH)] }}" >> $GITHUB_ENV
            echo "AZURE_CLIENT_SECRET=${{ secrets[format('{0}_AZURE_CLIENT_SECRET', env.BRANCH)] }}" >> $GITHUB_ENV
          fi # END AZURE_CLIENT_ID

      # Prepare build
      - run: taito build prepare:$BRANCH $IMAGE_TAG

      # Prepare artifacts for deployment
      - run: taito artifact prepare:wordpress:$BRANCH $IMAGE_TAG

      # Start VPN
      - name: Start VPN if BRANCH_OVPN_FILE and BRANCH_OVPN_PASSWORD configured
        env:
          OVPN_FILE: ${{ secrets['OVPN_FILE'] }}
          OVPN_PASSWORD: ${{ secrets['OVPN_PASSWORD'] }}
          BRANCH_OVPN_FILE: ${{ secrets[format('{0}_OVPN_FILE', env.BRANCH)] }}
          BRANCH_OVPN_PASSWORD: ${{ secrets[format('{0}_OVPN_PASSWORD', env.BRANCH)] }}
        run: |
          mkdir -p tmp
          echo "$OVPN_FILE" > tmp/vpn.ovpn
          echo "$OVPN_PASSWORD" > tmp/vpn.password
          echo "$BRANCH_OVPN_FILE" > tmp/branch-vpn.ovpn
          echo "$BRANCH_OVPN_PASSWORD" > tmp/branch-vpn.password
          if grep client tmp/branch-vpn.ovpn > /dev/null; then
            echo "askpass tmp/branch-vpn.password" >> tmp/branch-vpn.ovpn
            openvpn --daemon --config tmp/branch-vpn.ovpn
            sleep 10
          elif grep client tmp/vpn.ovpn > /dev/null; then
            echo "askpass tmp/vpn.password" >> tmp/vpn.ovpn
            openvpn --daemon --config tmp/vpn.ovpn
            sleep 10
          fi

      # Deploy changes to target environment
      - run: taito wp-plugin-update:$BRANCH  || echo "WARNING: Failed updating wordpress plugins"
      - run: taito deployment deploy:$BRANCH  $IMAGE_TAG

      # Release artifacts
      - run: taito artifact release:wordpress:$BRANCH $IMAGE_TAG

      # Release build
      - run: taito build release:$BRANCH


name: CI/CD Pipeline
on:
  push:
    branches:
      - dev
      - test
      - uat
      - stag
      - canary
      - prod
      - master
      - main

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-latest
    timeout-minutes: 50
    container:
      image: taitounited/taito-cli:ci-azure
      env:
        taito_mode: ci
        taito_image: taitounited/taito-cli:ci-azure
        taito_ci_phases:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        IMAGE_TAG: ${{ github.sha }}
    steps:
      # Prepare build
      - name: Check out the repo
        uses: actions/checkout@v2
      - run: taito build prepare:${GITHUB_REF##*/} $IMAGE_TAG

      # Prepare artifacts for deployment
      - run: taito artifact prepare:wordpress:${GITHUB_REF##*/} $IMAGE_TAG

      # Deploy changes to target environment
      - run: taito wp-plugin-update:${GITHUB_REF##*/} || echo "WARNING: Failed updating wordpress plugins"
      - run: taito deployment deploy:${GITHUB_REF##*/} $IMAGE_TAG

      # Release artifacts
      - run: taito artifact release:wordpress:${GITHUB_REF##*/} $IMAGE_TAG

      # Release build
      - run: taito build release:${GITHUB_REF##*/}
